package com.sia.model;
// Generated Apr 8, 2013 5:27:46 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Absensi generated by hbm2java
 */
public class Absensi  implements java.io.Serializable {


     private AbsensiId id;
     private Matkul matkul;
     private Dosen dosen;
     private Mahasiswa mahasiswa;
     private Ruangan ruangan;
     private Date tanggal;
     private String keterangan;

    public Absensi() {
    }

    public Absensi(AbsensiId id, Matkul matkul, Dosen dosen, Mahasiswa mahasiswa, Ruangan ruangan, Date tanggal, String keterangan) {
       this.id = id;
       this.matkul = matkul;
       this.dosen = dosen;
       this.mahasiswa = mahasiswa;
       this.ruangan = ruangan;
       this.tanggal = tanggal;
       this.keterangan = keterangan;
    }
   
    public AbsensiId getId() {
        return this.id;
    }
    
    public void setId(AbsensiId id) {
        this.id = id;
    }
    public Matkul getMatkul() {
        return this.matkul;
    }
    
    public void setMatkul(Matkul matkul) {
        this.matkul = matkul;
    }
    public Dosen getDosen() {
        return this.dosen;
    }
    
    public void setDosen(Dosen dosen) {
        this.dosen = dosen;
    }
    public Mahasiswa getMahasiswa() {
        return this.mahasiswa;
    }
    
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }
    public Ruangan getRuangan() {
        return this.ruangan;
    }
    
    public void setRuangan(Ruangan ruangan) {
        this.ruangan = ruangan;
    }
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }
    public String getKeterangan() {
        return this.keterangan;
    }
    
    public void setKeterangan(String keterangan) {
        this.keterangan = keterangan;
    }




}


