package com.sia.model;
// Generated Apr 8, 2013 5:27:46 PM by Hibernate Tools 3.2.1.GA



/**
 * AbsensiId generated by hbm2java
 */
public class AbsensiId  implements java.io.Serializable {


     private int nim;
     private int nikd;
     private int kodeMk;
     private int noRuang;

    public AbsensiId() {
    }

    public AbsensiId(int nim, int nikd, int kodeMk, int noRuang) {
       this.nim = nim;
       this.nikd = nikd;
       this.kodeMk = kodeMk;
       this.noRuang = noRuang;
    }
   
    public int getNim() {
        return this.nim;
    }
    
    public void setNim(int nim) {
        this.nim = nim;
    }
    public int getNikd() {
        return this.nikd;
    }
    
    public void setNikd(int nikd) {
        this.nikd = nikd;
    }
    public int getKodeMk() {
        return this.kodeMk;
    }
    
    public void setKodeMk(int kodeMk) {
        this.kodeMk = kodeMk;
    }
    public int getNoRuang() {
        return this.noRuang;
    }
    
    public void setNoRuang(int noRuang) {
        this.noRuang = noRuang;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbsensiId) ) return false;
		 AbsensiId castOther = ( AbsensiId ) other; 
         
		 return (this.getNim()==castOther.getNim())
 && (this.getNikd()==castOther.getNikd())
 && (this.getKodeMk()==castOther.getKodeMk())
 && (this.getNoRuang()==castOther.getNoRuang());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNim();
         result = 37 * result + this.getNikd();
         result = 37 * result + this.getKodeMk();
         result = 37 * result + this.getNoRuang();
         return result;
   }   


}


