package com.sia.model;
// Generated Apr 8, 2013 5:27:46 PM by Hibernate Tools 3.2.1.GA



/**
 * Ajar generated by hbm2java
 */
public class Ajar  implements java.io.Serializable {


     private AjarId id;
     private Dosen dosen;
     private Periodic periodic;
     private int bobot1;
     private int bobot2;
     private int bobot3;
     private int bobot4;
     private int bobot5;

    public Ajar() {
    }

    public Ajar(AjarId id, Dosen dosen, Periodic periodic, int bobot1, int bobot2, int bobot3, int bobot4, int bobot5) {
       this.id = id;
       this.dosen = dosen;
       this.periodic = periodic;
       this.bobot1 = bobot1;
       this.bobot2 = bobot2;
       this.bobot3 = bobot3;
       this.bobot4 = bobot4;
       this.bobot5 = bobot5;
    }
   
    public AjarId getId() {
        return this.id;
    }
    
    public void setId(AjarId id) {
        this.id = id;
    }
    public Dosen getDosen() {
        return this.dosen;
    }
    
    public void setDosen(Dosen dosen) {
        this.dosen = dosen;
    }
    public Periodic getPeriodic() {
        return this.periodic;
    }
    
    public void setPeriodic(Periodic periodic) {
        this.periodic = periodic;
    }
    public int getBobot1() {
        return this.bobot1;
    }
    
    public void setBobot1(int bobot1) {
        this.bobot1 = bobot1;
    }
    public int getBobot2() {
        return this.bobot2;
    }
    
    public void setBobot2(int bobot2) {
        this.bobot2 = bobot2;
    }
    public int getBobot3() {
        return this.bobot3;
    }
    
    public void setBobot3(int bobot3) {
        this.bobot3 = bobot3;
    }
    public int getBobot4() {
        return this.bobot4;
    }
    
    public void setBobot4(int bobot4) {
        this.bobot4 = bobot4;
    }
    public int getBobot5() {
        return this.bobot5;
    }
    
    public void setBobot5(int bobot5) {
        this.bobot5 = bobot5;
    }




}


