package com.sia.model;
// Generated Apr 8, 2013 5:27:46 PM by Hibernate Tools 3.2.1.GA



/**
 * Ambil generated by hbm2java
 */
public class Ambil  implements java.io.Serializable {


     private AmbilId id;
     private Matkul matkul;
     private Mahasiswa mahasiswa;
     private Periodic periodic;
     private Departemen departemen;
     private String kelas;
     private String semester;
     private int nilai1;
     private int nilai2;
     private int nilai3;
     private int nilai4;
     private int nilai5;

    public Ambil() {
    }

    public Ambil(AmbilId id, Matkul matkul, Mahasiswa mahasiswa, Periodic periodic, Departemen departemen, String kelas, String semester, int nilai1, int nilai2, int nilai3, int nilai4, int nilai5) {
       this.id = id;
       this.matkul = matkul;
       this.mahasiswa = mahasiswa;
       this.periodic = periodic;
       this.departemen = departemen;
       this.kelas = kelas;
       this.semester = semester;
       this.nilai1 = nilai1;
       this.nilai2 = nilai2;
       this.nilai3 = nilai3;
       this.nilai4 = nilai4;
       this.nilai5 = nilai5;
    }
   
    public AmbilId getId() {
        return this.id;
    }
    
    public void setId(AmbilId id) {
        this.id = id;
    }
    public Matkul getMatkul() {
        return this.matkul;
    }
    
    public void setMatkul(Matkul matkul) {
        this.matkul = matkul;
    }
    public Mahasiswa getMahasiswa() {
        return this.mahasiswa;
    }
    
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }
    public Periodic getPeriodic() {
        return this.periodic;
    }
    
    public void setPeriodic(Periodic periodic) {
        this.periodic = periodic;
    }
    public Departemen getDepartemen() {
        return this.departemen;
    }
    
    public void setDepartemen(Departemen departemen) {
        this.departemen = departemen;
    }
    public String getKelas() {
        return this.kelas;
    }
    
    public void setKelas(String kelas) {
        this.kelas = kelas;
    }
    public String getSemester() {
        return this.semester;
    }
    
    public void setSemester(String semester) {
        this.semester = semester;
    }
    public int getNilai1() {
        return this.nilai1;
    }
    
    public void setNilai1(int nilai1) {
        this.nilai1 = nilai1;
    }
    public int getNilai2() {
        return this.nilai2;
    }
    
    public void setNilai2(int nilai2) {
        this.nilai2 = nilai2;
    }
    public int getNilai3() {
        return this.nilai3;
    }
    
    public void setNilai3(int nilai3) {
        this.nilai3 = nilai3;
    }
    public int getNilai4() {
        return this.nilai4;
    }
    
    public void setNilai4(int nilai4) {
        this.nilai4 = nilai4;
    }
    public int getNilai5() {
        return this.nilai5;
    }
    
    public void setNilai5(int nilai5) {
        this.nilai5 = nilai5;
    }




}


