package com.sia.model;
// Generated Apr 8, 2013 5:27:46 PM by Hibernate Tools 3.2.1.GA



/**
 * AmbilId generated by hbm2java
 */
public class AmbilId  implements java.io.Serializable {


     private int nim;
     private int kodeMk;
     private int idDept;
     private int idPeriodic;

    public AmbilId() {
    }

    public AmbilId(int nim, int kodeMk, int idDept, int idPeriodic) {
       this.nim = nim;
       this.kodeMk = kodeMk;
       this.idDept = idDept;
       this.idPeriodic = idPeriodic;
    }
   
    public int getNim() {
        return this.nim;
    }
    
    public void setNim(int nim) {
        this.nim = nim;
    }
    public int getKodeMk() {
        return this.kodeMk;
    }
    
    public void setKodeMk(int kodeMk) {
        this.kodeMk = kodeMk;
    }
    public int getIdDept() {
        return this.idDept;
    }
    
    public void setIdDept(int idDept) {
        this.idDept = idDept;
    }
    public int getIdPeriodic() {
        return this.idPeriodic;
    }
    
    public void setIdPeriodic(int idPeriodic) {
        this.idPeriodic = idPeriodic;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmbilId) ) return false;
		 AmbilId castOther = ( AmbilId ) other; 
         
		 return (this.getNim()==castOther.getNim())
 && (this.getKodeMk()==castOther.getKodeMk())
 && (this.getIdDept()==castOther.getIdDept())
 && (this.getIdPeriodic()==castOther.getIdPeriodic());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNim();
         result = 37 * result + this.getKodeMk();
         result = 37 * result + this.getIdDept();
         result = 37 * result + this.getIdPeriodic();
         return result;
   }   


}


