package com.sia.model;
// Generated Apr 8, 2013 5:27:46 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Biaya generated by hbm2java
 */
public class Biaya  implements java.io.Serializable {


     private int angkatan;
     private int BSks;
     private int BSemester;
     private Set<Transaksi> transaksis = new HashSet<Transaksi>(0);

    public Biaya() {
    }

	
    public Biaya(int angkatan, int BSks, int BSemester) {
        this.angkatan = angkatan;
        this.BSks = BSks;
        this.BSemester = BSemester;
    }
    public Biaya(int angkatan, int BSks, int BSemester, Set<Transaksi> transaksis) {
       this.angkatan = angkatan;
       this.BSks = BSks;
       this.BSemester = BSemester;
       this.transaksis = transaksis;
    }
   
    public int getAngkatan() {
        return this.angkatan;
    }
    
    public void setAngkatan(int angkatan) {
        this.angkatan = angkatan;
    }
    public int getBSks() {
        return this.BSks;
    }
    
    public void setBSks(int BSks) {
        this.BSks = BSks;
    }
    public int getBSemester() {
        return this.BSemester;
    }
    
    public void setBSemester(int BSemester) {
        this.BSemester = BSemester;
    }
    public Set<Transaksi> getTransaksis() {
        return this.transaksis;
    }
    
    public void setTransaksis(Set<Transaksi> transaksis) {
        this.transaksis = transaksis;
    }




}


