package com.sia.model;
// Generated Apr 8, 2013 5:27:46 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Departemen generated by hbm2java
 */
public class Departemen  implements java.io.Serializable {


     private int idDept;
     private Dosen dosen;
     private Fakultas fakultas;
     private String namaJurusan;
     private Set<Kurikulum> kurikulums = new HashSet<Kurikulum>(0);
     private Set<Ambil> ambils = new HashSet<Ambil>(0);
     private Set<Mahasiswa> mahasiswas = new HashSet<Mahasiswa>(0);

    public Departemen() {
    }

	
    public Departemen(int idDept, Dosen dosen, Fakultas fakultas, String namaJurusan) {
        this.idDept = idDept;
        this.dosen = dosen;
        this.fakultas = fakultas;
        this.namaJurusan = namaJurusan;
    }
    public Departemen(int idDept, Dosen dosen, Fakultas fakultas, String namaJurusan, Set<Kurikulum> kurikulums, Set<Ambil> ambils, Set<Mahasiswa> mahasiswas) {
       this.idDept = idDept;
       this.dosen = dosen;
       this.fakultas = fakultas;
       this.namaJurusan = namaJurusan;
       this.kurikulums = kurikulums;
       this.ambils = ambils;
       this.mahasiswas = mahasiswas;
    }
   
    public int getIdDept() {
        return this.idDept;
    }
    
    public void setIdDept(int idDept) {
        this.idDept = idDept;
    }
    public Dosen getDosen() {
        return this.dosen;
    }
    
    public void setDosen(Dosen dosen) {
        this.dosen = dosen;
    }
    public Fakultas getFakultas() {
        return this.fakultas;
    }
    
    public void setFakultas(Fakultas fakultas) {
        this.fakultas = fakultas;
    }
    public String getNamaJurusan() {
        return this.namaJurusan;
    }
    
    public void setNamaJurusan(String namaJurusan) {
        this.namaJurusan = namaJurusan;
    }
    public Set<Kurikulum> getKurikulums() {
        return this.kurikulums;
    }
    
    public void setKurikulums(Set<Kurikulum> kurikulums) {
        this.kurikulums = kurikulums;
    }
    public Set<Ambil> getAmbils() {
        return this.ambils;
    }
    
    public void setAmbils(Set<Ambil> ambils) {
        this.ambils = ambils;
    }
    public Set<Mahasiswa> getMahasiswas() {
        return this.mahasiswas;
    }
    
    public void setMahasiswas(Set<Mahasiswa> mahasiswas) {
        this.mahasiswas = mahasiswas;
    }




}


