package com.sia.model;
// Generated Apr 8, 2013 5:27:46 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Dosen generated by hbm2java
 */
public class Dosen  implements java.io.Serializable {


     private int nikd;
     private Hakakses hakakses;
     private String nama;
     private String jabatan;
     private String passDs;
     private Set<Jadwal> jadwals = new HashSet<Jadwal>(0);
     private Set<Absensi> absensis = new HashSet<Absensi>(0);
     private Set<Departemen> departemens = new HashSet<Departemen>(0);
     private Set<Ajar> ajars = new HashSet<Ajar>(0);

    public Dosen() {
    }

	
    public Dosen(int nikd, Hakakses hakakses, String nama, String jabatan, String passDs) {
        this.nikd = nikd;
        this.hakakses = hakakses;
        this.nama = nama;
        this.jabatan = jabatan;
        this.passDs = passDs;
    }
    public Dosen(int nikd, Hakakses hakakses, String nama, String jabatan, String passDs, Set<Jadwal> jadwals, Set<Absensi> absensis, Set<Departemen> departemens, Set<Ajar> ajars) {
       this.nikd = nikd;
       this.hakakses = hakakses;
       this.nama = nama;
       this.jabatan = jabatan;
       this.passDs = passDs;
       this.jadwals = jadwals;
       this.absensis = absensis;
       this.departemens = departemens;
       this.ajars = ajars;
    }
   
    public int getNikd() {
        return this.nikd;
    }
    
    public void setNikd(int nikd) {
        this.nikd = nikd;
    }
    public Hakakses getHakakses() {
        return this.hakakses;
    }
    
    public void setHakakses(Hakakses hakakses) {
        this.hakakses = hakakses;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getJabatan() {
        return this.jabatan;
    }
    
    public void setJabatan(String jabatan) {
        this.jabatan = jabatan;
    }
    public String getPassDs() {
        return this.passDs;
    }
    
    public void setPassDs(String passDs) {
        this.passDs = passDs;
    }
    public Set<Jadwal> getJadwals() {
        return this.jadwals;
    }
    
    public void setJadwals(Set<Jadwal> jadwals) {
        this.jadwals = jadwals;
    }
    public Set<Absensi> getAbsensis() {
        return this.absensis;
    }
    
    public void setAbsensis(Set<Absensi> absensis) {
        this.absensis = absensis;
    }
    public Set<Departemen> getDepartemens() {
        return this.departemens;
    }
    
    public void setDepartemens(Set<Departemen> departemens) {
        this.departemens = departemens;
    }
    public Set<Ajar> getAjars() {
        return this.ajars;
    }
    
    public void setAjars(Set<Ajar> ajars) {
        this.ajars = ajars;
    }




}


