package com.sia.model;
// Generated Apr 8, 2013 5:27:46 PM by Hibernate Tools 3.2.1.GA



/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private int nik;
     private String nama;

    public Employee() {
    }

    public Employee(int nik, String nama) {
       this.nik = nik;
       this.nama = nama;
    }
   
    public int getNik() {
        return this.nik;
    }
    
    public void setNik(int nik) {
        this.nik = nik;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }




}


