package com.sia.model;
// Generated Apr 8, 2013 5:27:46 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hakakses generated by hbm2java
 */
public class Hakakses  implements java.io.Serializable {


     private int idAkses;
     private String pengakses;
     private int edit;
     private int modulDataUser;
     private int modulDataMhsDosenStaff;
     private int modulMkpengajar;
     private int modulNilaiTranskripMhs;
     private int modulKeuangan;
     private int modulBahanKuliah;
     private int modulKrsonline;
     private int modulBakcup;
     private int modulAbsensiMhs;
     private Set<Mahasiswa> mahasiswas = new HashSet<Mahasiswa>(0);
     private Set<Dosen> dosens = new HashSet<Dosen>(0);
     private Set<Staff> staffs = new HashSet<Staff>(0);

    public Hakakses() {
    }

	
    public Hakakses(int idAkses, String pengakses, int edit, int modulDataUser, int modulDataMhsDosenStaff, int modulMkpengajar, int modulNilaiTranskripMhs, int modulKeuangan, int modulBahanKuliah, int modulKrsonline, int modulBakcup, int modulAbsensiMhs) {
        this.idAkses = idAkses;
        this.pengakses = pengakses;
        this.edit = edit;
        this.modulDataUser = modulDataUser;
        this.modulDataMhsDosenStaff = modulDataMhsDosenStaff;
        this.modulMkpengajar = modulMkpengajar;
        this.modulNilaiTranskripMhs = modulNilaiTranskripMhs;
        this.modulKeuangan = modulKeuangan;
        this.modulBahanKuliah = modulBahanKuliah;
        this.modulKrsonline = modulKrsonline;
        this.modulBakcup = modulBakcup;
        this.modulAbsensiMhs = modulAbsensiMhs;
    }
    public Hakakses(int idAkses, String pengakses, int edit, int modulDataUser, int modulDataMhsDosenStaff, int modulMkpengajar, int modulNilaiTranskripMhs, int modulKeuangan, int modulBahanKuliah, int modulKrsonline, int modulBakcup, int modulAbsensiMhs, Set<Mahasiswa> mahasiswas, Set<Dosen> dosens, Set<Staff> staffs) {
       this.idAkses = idAkses;
       this.pengakses = pengakses;
       this.edit = edit;
       this.modulDataUser = modulDataUser;
       this.modulDataMhsDosenStaff = modulDataMhsDosenStaff;
       this.modulMkpengajar = modulMkpengajar;
       this.modulNilaiTranskripMhs = modulNilaiTranskripMhs;
       this.modulKeuangan = modulKeuangan;
       this.modulBahanKuliah = modulBahanKuliah;
       this.modulKrsonline = modulKrsonline;
       this.modulBakcup = modulBakcup;
       this.modulAbsensiMhs = modulAbsensiMhs;
       this.mahasiswas = mahasiswas;
       this.dosens = dosens;
       this.staffs = staffs;
    }
   
    public int getIdAkses() {
        return this.idAkses;
    }
    
    public void setIdAkses(int idAkses) {
        this.idAkses = idAkses;
    }
    public String getPengakses() {
        return this.pengakses;
    }
    
    public void setPengakses(String pengakses) {
        this.pengakses = pengakses;
    }
    public int getEdit() {
        return this.edit;
    }
    
    public void setEdit(int edit) {
        this.edit = edit;
    }
    public int getModulDataUser() {
        return this.modulDataUser;
    }
    
    public void setModulDataUser(int modulDataUser) {
        this.modulDataUser = modulDataUser;
    }
    public int getModulDataMhsDosenStaff() {
        return this.modulDataMhsDosenStaff;
    }
    
    public void setModulDataMhsDosenStaff(int modulDataMhsDosenStaff) {
        this.modulDataMhsDosenStaff = modulDataMhsDosenStaff;
    }
    public int getModulMkpengajar() {
        return this.modulMkpengajar;
    }
    
    public void setModulMkpengajar(int modulMkpengajar) {
        this.modulMkpengajar = modulMkpengajar;
    }
    public int getModulNilaiTranskripMhs() {
        return this.modulNilaiTranskripMhs;
    }
    
    public void setModulNilaiTranskripMhs(int modulNilaiTranskripMhs) {
        this.modulNilaiTranskripMhs = modulNilaiTranskripMhs;
    }
    public int getModulKeuangan() {
        return this.modulKeuangan;
    }
    
    public void setModulKeuangan(int modulKeuangan) {
        this.modulKeuangan = modulKeuangan;
    }
    public int getModulBahanKuliah() {
        return this.modulBahanKuliah;
    }
    
    public void setModulBahanKuliah(int modulBahanKuliah) {
        this.modulBahanKuliah = modulBahanKuliah;
    }
    public int getModulKrsonline() {
        return this.modulKrsonline;
    }
    
    public void setModulKrsonline(int modulKrsonline) {
        this.modulKrsonline = modulKrsonline;
    }
    public int getModulBakcup() {
        return this.modulBakcup;
    }
    
    public void setModulBakcup(int modulBakcup) {
        this.modulBakcup = modulBakcup;
    }
    public int getModulAbsensiMhs() {
        return this.modulAbsensiMhs;
    }
    
    public void setModulAbsensiMhs(int modulAbsensiMhs) {
        this.modulAbsensiMhs = modulAbsensiMhs;
    }
    public Set<Mahasiswa> getMahasiswas() {
        return this.mahasiswas;
    }
    
    public void setMahasiswas(Set<Mahasiswa> mahasiswas) {
        this.mahasiswas = mahasiswas;
    }
    public Set<Dosen> getDosens() {
        return this.dosens;
    }
    
    public void setDosens(Set<Dosen> dosens) {
        this.dosens = dosens;
    }
    public Set<Staff> getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set<Staff> staffs) {
        this.staffs = staffs;
    }




}


