package com.sia.model;
// Generated Apr 8, 2013 5:27:46 PM by Hibernate Tools 3.2.1.GA



/**
 * Jadwal generated by hbm2java
 */
public class Jadwal  implements java.io.Serializable {


     private JadwalId id;
     private Matkul matkul;
     private Dosen dosen;
     private Ruangan ruangan;
     private String jamMulai;
     private String jamAkhir;
     private String hari;
     private String kelas;

    public Jadwal() {
    }

    public Jadwal(JadwalId id, Matkul matkul, Dosen dosen, Ruangan ruangan, String jamMulai, String jamAkhir, String hari, String kelas) {
       this.id = id;
       this.matkul = matkul;
       this.dosen = dosen;
       this.ruangan = ruangan;
       this.jamMulai = jamMulai;
       this.jamAkhir = jamAkhir;
       this.hari = hari;
       this.kelas = kelas;
    }
   
    public JadwalId getId() {
        return this.id;
    }
    
    public void setId(JadwalId id) {
        this.id = id;
    }
    public Matkul getMatkul() {
        return this.matkul;
    }
    
    public void setMatkul(Matkul matkul) {
        this.matkul = matkul;
    }
    public Dosen getDosen() {
        return this.dosen;
    }
    
    public void setDosen(Dosen dosen) {
        this.dosen = dosen;
    }
    public Ruangan getRuangan() {
        return this.ruangan;
    }
    
    public void setRuangan(Ruangan ruangan) {
        this.ruangan = ruangan;
    }
    public String getJamMulai() {
        return this.jamMulai;
    }
    
    public void setJamMulai(String jamMulai) {
        this.jamMulai = jamMulai;
    }
    public String getJamAkhir() {
        return this.jamAkhir;
    }
    
    public void setJamAkhir(String jamAkhir) {
        this.jamAkhir = jamAkhir;
    }
    public String getHari() {
        return this.hari;
    }
    
    public void setHari(String hari) {
        this.hari = hari;
    }
    public String getKelas() {
        return this.kelas;
    }
    
    public void setKelas(String kelas) {
        this.kelas = kelas;
    }




}


