package com.sia.model;
// Generated Apr 8, 2013 5:27:46 PM by Hibernate Tools 3.2.1.GA



/**
 * JadwalId generated by hbm2java
 */
public class JadwalId  implements java.io.Serializable {


     private int noRuang;
     private int nikd;
     private int kodeMk;

    public JadwalId() {
    }

    public JadwalId(int noRuang, int nikd, int kodeMk) {
       this.noRuang = noRuang;
       this.nikd = nikd;
       this.kodeMk = kodeMk;
    }
   
    public int getNoRuang() {
        return this.noRuang;
    }
    
    public void setNoRuang(int noRuang) {
        this.noRuang = noRuang;
    }
    public int getNikd() {
        return this.nikd;
    }
    
    public void setNikd(int nikd) {
        this.nikd = nikd;
    }
    public int getKodeMk() {
        return this.kodeMk;
    }
    
    public void setKodeMk(int kodeMk) {
        this.kodeMk = kodeMk;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JadwalId) ) return false;
		 JadwalId castOther = ( JadwalId ) other; 
         
		 return (this.getNoRuang()==castOther.getNoRuang())
 && (this.getNikd()==castOther.getNikd())
 && (this.getKodeMk()==castOther.getKodeMk());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNoRuang();
         result = 37 * result + this.getNikd();
         result = 37 * result + this.getKodeMk();
         return result;
   }   


}


