package com.sia.model;
// Generated Apr 8, 2013 5:27:46 PM by Hibernate Tools 3.2.1.GA



/**
 * Kurikulum generated by hbm2java
 */
public class Kurikulum  implements java.io.Serializable {


     private KurikulumId id;
     private Periodic periodic;
     private Departemen departemen;

    public Kurikulum() {
    }

    public Kurikulum(KurikulumId id, Periodic periodic, Departemen departemen) {
       this.id = id;
       this.periodic = periodic;
       this.departemen = departemen;
    }
   
    public KurikulumId getId() {
        return this.id;
    }
    
    public void setId(KurikulumId id) {
        this.id = id;
    }
    public Periodic getPeriodic() {
        return this.periodic;
    }
    
    public void setPeriodic(Periodic periodic) {
        this.periodic = periodic;
    }
    public Departemen getDepartemen() {
        return this.departemen;
    }
    
    public void setDepartemen(Departemen departemen) {
        this.departemen = departemen;
    }




}


