package com.sia.model;
// Generated Apr 8, 2013 5:27:46 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Matkul generated by hbm2java
 */
public class Matkul  implements java.io.Serializable {


     private int kodeMk;
     private String namaMk;
     private int jmlSks;
     private String ketSemester;
     private String sifat;
     private Set<Tugaskul> tugaskuls = new HashSet<Tugaskul>(0);
     private Set<Jadwal> jadwals = new HashSet<Jadwal>(0);
     private Set<Bahankul> bahankuls = new HashSet<Bahankul>(0);
     private Set<Absensi> absensis = new HashSet<Absensi>(0);
     private Set<Transaksi> transaksis = new HashSet<Transaksi>(0);
     private Set<Ambil> ambils = new HashSet<Ambil>(0);

    public Matkul() {
    }

	
    public Matkul(int kodeMk, String namaMk, int jmlSks, String ketSemester, String sifat) {
        this.kodeMk = kodeMk;
        this.namaMk = namaMk;
        this.jmlSks = jmlSks;
        this.ketSemester = ketSemester;
        this.sifat = sifat;
    }
    public Matkul(int kodeMk, String namaMk, int jmlSks, String ketSemester, String sifat, Set<Tugaskul> tugaskuls, Set<Jadwal> jadwals, Set<Bahankul> bahankuls, Set<Absensi> absensis, Set<Transaksi> transaksis, Set<Ambil> ambils) {
       this.kodeMk = kodeMk;
       this.namaMk = namaMk;
       this.jmlSks = jmlSks;
       this.ketSemester = ketSemester;
       this.sifat = sifat;
       this.tugaskuls = tugaskuls;
       this.jadwals = jadwals;
       this.bahankuls = bahankuls;
       this.absensis = absensis;
       this.transaksis = transaksis;
       this.ambils = ambils;
    }
   
    public int getKodeMk() {
        return this.kodeMk;
    }
    
    public void setKodeMk(int kodeMk) {
        this.kodeMk = kodeMk;
    }
    public String getNamaMk() {
        return this.namaMk;
    }
    
    public void setNamaMk(String namaMk) {
        this.namaMk = namaMk;
    }
    public int getJmlSks() {
        return this.jmlSks;
    }
    
    public void setJmlSks(int jmlSks) {
        this.jmlSks = jmlSks;
    }
    public String getKetSemester() {
        return this.ketSemester;
    }
    
    public void setKetSemester(String ketSemester) {
        this.ketSemester = ketSemester;
    }
    public String getSifat() {
        return this.sifat;
    }
    
    public void setSifat(String sifat) {
        this.sifat = sifat;
    }
    public Set<Tugaskul> getTugaskuls() {
        return this.tugaskuls;
    }
    
    public void setTugaskuls(Set<Tugaskul> tugaskuls) {
        this.tugaskuls = tugaskuls;
    }
    public Set<Jadwal> getJadwals() {
        return this.jadwals;
    }
    
    public void setJadwals(Set<Jadwal> jadwals) {
        this.jadwals = jadwals;
    }
    public Set<Bahankul> getBahankuls() {
        return this.bahankuls;
    }
    
    public void setBahankuls(Set<Bahankul> bahankuls) {
        this.bahankuls = bahankuls;
    }
    public Set<Absensi> getAbsensis() {
        return this.absensis;
    }
    
    public void setAbsensis(Set<Absensi> absensis) {
        this.absensis = absensis;
    }
    public Set<Transaksi> getTransaksis() {
        return this.transaksis;
    }
    
    public void setTransaksis(Set<Transaksi> transaksis) {
        this.transaksis = transaksis;
    }
    public Set<Ambil> getAmbils() {
        return this.ambils;
    }
    
    public void setAmbils(Set<Ambil> ambils) {
        this.ambils = ambils;
    }




}


