package com.sia.model;
// Generated Apr 8, 2013 5:27:46 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Periodic generated by hbm2java
 */
public class Periodic  implements java.io.Serializable {


     private int idPerodic;
     private int tahunMulai;
     private int tahunAkhir;
     private Date tglKuliah;
     private Date tglAkhirKuliah;
     private Date tglKrs;
     private Date tglPrs;
     private Set<Kurikulum> kurikulums = new HashSet<Kurikulum>(0);
     private Set<Transaksi> transaksis = new HashSet<Transaksi>(0);
     private Set<Recordips> recordipses = new HashSet<Recordips>(0);
     private Set<Ajar> ajars = new HashSet<Ajar>(0);
     private Set<Ambil> ambils = new HashSet<Ambil>(0);

    public Periodic() {
    }

	
    public Periodic(int idPerodic, int tahunMulai, int tahunAkhir, Date tglKuliah, Date tglAkhirKuliah, Date tglKrs, Date tglPrs) {
        this.idPerodic = idPerodic;
        this.tahunMulai = tahunMulai;
        this.tahunAkhir = tahunAkhir;
        this.tglKuliah = tglKuliah;
        this.tglAkhirKuliah = tglAkhirKuliah;
        this.tglKrs = tglKrs;
        this.tglPrs = tglPrs;
    }
    public Periodic(int idPerodic, int tahunMulai, int tahunAkhir, Date tglKuliah, Date tglAkhirKuliah, Date tglKrs, Date tglPrs, Set<Kurikulum> kurikulums, Set<Transaksi> transaksis, Set<Recordips> recordipses, Set<Ajar> ajars, Set<Ambil> ambils) {
       this.idPerodic = idPerodic;
       this.tahunMulai = tahunMulai;
       this.tahunAkhir = tahunAkhir;
       this.tglKuliah = tglKuliah;
       this.tglAkhirKuliah = tglAkhirKuliah;
       this.tglKrs = tglKrs;
       this.tglPrs = tglPrs;
       this.kurikulums = kurikulums;
       this.transaksis = transaksis;
       this.recordipses = recordipses;
       this.ajars = ajars;
       this.ambils = ambils;
    }
   
    public int getIdPerodic() {
        return this.idPerodic;
    }
    
    public void setIdPerodic(int idPerodic) {
        this.idPerodic = idPerodic;
    }
    public int getTahunMulai() {
        return this.tahunMulai;
    }
    
    public void setTahunMulai(int tahunMulai) {
        this.tahunMulai = tahunMulai;
    }
    public int getTahunAkhir() {
        return this.tahunAkhir;
    }
    
    public void setTahunAkhir(int tahunAkhir) {
        this.tahunAkhir = tahunAkhir;
    }
    public Date getTglKuliah() {
        return this.tglKuliah;
    }
    
    public void setTglKuliah(Date tglKuliah) {
        this.tglKuliah = tglKuliah;
    }
    public Date getTglAkhirKuliah() {
        return this.tglAkhirKuliah;
    }
    
    public void setTglAkhirKuliah(Date tglAkhirKuliah) {
        this.tglAkhirKuliah = tglAkhirKuliah;
    }
    public Date getTglKrs() {
        return this.tglKrs;
    }
    
    public void setTglKrs(Date tglKrs) {
        this.tglKrs = tglKrs;
    }
    public Date getTglPrs() {
        return this.tglPrs;
    }
    
    public void setTglPrs(Date tglPrs) {
        this.tglPrs = tglPrs;
    }
    public Set<Kurikulum> getKurikulums() {
        return this.kurikulums;
    }
    
    public void setKurikulums(Set<Kurikulum> kurikulums) {
        this.kurikulums = kurikulums;
    }
    public Set<Transaksi> getTransaksis() {
        return this.transaksis;
    }
    
    public void setTransaksis(Set<Transaksi> transaksis) {
        this.transaksis = transaksis;
    }
    public Set<Recordips> getRecordipses() {
        return this.recordipses;
    }
    
    public void setRecordipses(Set<Recordips> recordipses) {
        this.recordipses = recordipses;
    }
    public Set<Ajar> getAjars() {
        return this.ajars;
    }
    
    public void setAjars(Set<Ajar> ajars) {
        this.ajars = ajars;
    }
    public Set<Ambil> getAmbils() {
        return this.ambils;
    }
    
    public void setAmbils(Set<Ambil> ambils) {
        this.ambils = ambils;
    }




}


