package com.sia.model;
// Generated Apr 8, 2013 5:27:46 PM by Hibernate Tools 3.2.1.GA



/**
 * RecordipsId generated by hbm2java
 */
public class RecordipsId  implements java.io.Serializable {


     private int idSemester;
     private int nim;
     private int idPeriodic;

    public RecordipsId() {
    }

    public RecordipsId(int idSemester, int nim, int idPeriodic) {
       this.idSemester = idSemester;
       this.nim = nim;
       this.idPeriodic = idPeriodic;
    }
   
    public int getIdSemester() {
        return this.idSemester;
    }
    
    public void setIdSemester(int idSemester) {
        this.idSemester = idSemester;
    }
    public int getNim() {
        return this.nim;
    }
    
    public void setNim(int nim) {
        this.nim = nim;
    }
    public int getIdPeriodic() {
        return this.idPeriodic;
    }
    
    public void setIdPeriodic(int idPeriodic) {
        this.idPeriodic = idPeriodic;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RecordipsId) ) return false;
		 RecordipsId castOther = ( RecordipsId ) other; 
         
		 return (this.getIdSemester()==castOther.getIdSemester())
 && (this.getNim()==castOther.getNim())
 && (this.getIdPeriodic()==castOther.getIdPeriodic());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdSemester();
         result = 37 * result + this.getNim();
         result = 37 * result + this.getIdPeriodic();
         return result;
   }   


}


