package com.sia.model;
// Generated Apr 8, 2013 5:27:46 PM by Hibernate Tools 3.2.1.GA



/**
 * Recordips generated by hbm2java
 */
public class Recordips  implements java.io.Serializable {


     private RecordipsId id;
     private Semester semester;
     private Mahasiswa mahasiswa;
     private Periodic periodic;
     private double nilaiIps;

    public Recordips() {
    }

    public Recordips(RecordipsId id, Semester semester, Mahasiswa mahasiswa, Periodic periodic, double nilaiIps) {
       this.id = id;
       this.semester = semester;
       this.mahasiswa = mahasiswa;
       this.periodic = periodic;
       this.nilaiIps = nilaiIps;
    }
   
    public RecordipsId getId() {
        return this.id;
    }
    
    public void setId(RecordipsId id) {
        this.id = id;
    }
    public Semester getSemester() {
        return this.semester;
    }
    
    public void setSemester(Semester semester) {
        this.semester = semester;
    }
    public Mahasiswa getMahasiswa() {
        return this.mahasiswa;
    }
    
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }
    public Periodic getPeriodic() {
        return this.periodic;
    }
    
    public void setPeriodic(Periodic periodic) {
        this.periodic = periodic;
    }
    public double getNilaiIps() {
        return this.nilaiIps;
    }
    
    public void setNilaiIps(double nilaiIps) {
        this.nilaiIps = nilaiIps;
    }




}


