package com.sia.model;
// Generated Apr 8, 2013 5:27:46 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Ruangan generated by hbm2java
 */
public class Ruangan  implements java.io.Serializable {


     private int noRuang;
     private String lantai;
     private int jmlKursi;
     private Set<Absensi> absensis = new HashSet<Absensi>(0);
     private Set<Jadwal> jadwals = new HashSet<Jadwal>(0);

    public Ruangan() {
    }

	
    public Ruangan(int noRuang, String lantai, int jmlKursi) {
        this.noRuang = noRuang;
        this.lantai = lantai;
        this.jmlKursi = jmlKursi;
    }
    public Ruangan(int noRuang, String lantai, int jmlKursi, Set<Absensi> absensis, Set<Jadwal> jadwals) {
       this.noRuang = noRuang;
       this.lantai = lantai;
       this.jmlKursi = jmlKursi;
       this.absensis = absensis;
       this.jadwals = jadwals;
    }
   
    public int getNoRuang() {
        return this.noRuang;
    }
    
    public void setNoRuang(int noRuang) {
        this.noRuang = noRuang;
    }
    public String getLantai() {
        return this.lantai;
    }
    
    public void setLantai(String lantai) {
        this.lantai = lantai;
    }
    public int getJmlKursi() {
        return this.jmlKursi;
    }
    
    public void setJmlKursi(int jmlKursi) {
        this.jmlKursi = jmlKursi;
    }
    public Set<Absensi> getAbsensis() {
        return this.absensis;
    }
    
    public void setAbsensis(Set<Absensi> absensis) {
        this.absensis = absensis;
    }
    public Set<Jadwal> getJadwals() {
        return this.jadwals;
    }
    
    public void setJadwals(Set<Jadwal> jadwals) {
        this.jadwals = jadwals;
    }




}


