package com.sia.model;
// Generated Apr 8, 2013 5:27:46 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Semester generated by hbm2java
 */
public class Semester  implements java.io.Serializable {


     private int idSemester;
     private String status;
     private Set<Recordips> recordipses = new HashSet<Recordips>(0);

    public Semester() {
    }

	
    public Semester(int idSemester, String status) {
        this.idSemester = idSemester;
        this.status = status;
    }
    public Semester(int idSemester, String status, Set<Recordips> recordipses) {
       this.idSemester = idSemester;
       this.status = status;
       this.recordipses = recordipses;
    }
   
    public int getIdSemester() {
        return this.idSemester;
    }
    
    public void setIdSemester(int idSemester) {
        this.idSemester = idSemester;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<Recordips> getRecordipses() {
        return this.recordipses;
    }
    
    public void setRecordipses(Set<Recordips> recordipses) {
        this.recordipses = recordipses;
    }




}


