package com.sia.model;
// Generated Apr 8, 2013 5:27:46 PM by Hibernate Tools 3.2.1.GA



/**
 * Staff generated by hbm2java
 */
public class Staff  implements java.io.Serializable {


     private int niks;
     private Hakakses hakakses;
     private String nama;
     private String passSt;

    public Staff() {
    }

    public Staff(int niks, Hakakses hakakses, String nama, String passSt) {
       this.niks = niks;
       this.hakakses = hakakses;
       this.nama = nama;
       this.passSt = passSt;
    }
   
    public int getNiks() {
        return this.niks;
    }
    
    public void setNiks(int niks) {
        this.niks = niks;
    }
    public Hakakses getHakakses() {
        return this.hakakses;
    }
    
    public void setHakakses(Hakakses hakakses) {
        this.hakakses = hakakses;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getPassSt() {
        return this.passSt;
    }
    
    public void setPassSt(String passSt) {
        this.passSt = passSt;
    }




}


