package com.sia.model;
// Generated Apr 8, 2013 5:27:46 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tugaskul generated by hbm2java
 */
public class Tugaskul  implements java.io.Serializable {


     private int idTugas;
     private Matkul matkul;
     private Date tglPemberian;
     private Date tglPengumpulan;
     private String deskripsi;

    public Tugaskul() {
    }

    public Tugaskul(int idTugas, Matkul matkul, Date tglPemberian, Date tglPengumpulan, String deskripsi) {
       this.idTugas = idTugas;
       this.matkul = matkul;
       this.tglPemberian = tglPemberian;
       this.tglPengumpulan = tglPengumpulan;
       this.deskripsi = deskripsi;
    }
   
    public int getIdTugas() {
        return this.idTugas;
    }
    
    public void setIdTugas(int idTugas) {
        this.idTugas = idTugas;
    }
    public Matkul getMatkul() {
        return this.matkul;
    }
    
    public void setMatkul(Matkul matkul) {
        this.matkul = matkul;
    }
    public Date getTglPemberian() {
        return this.tglPemberian;
    }
    
    public void setTglPemberian(Date tglPemberian) {
        this.tglPemberian = tglPemberian;
    }
    public Date getTglPengumpulan() {
        return this.tglPengumpulan;
    }
    
    public void setTglPengumpulan(Date tglPengumpulan) {
        this.tglPengumpulan = tglPengumpulan;
    }
    public String getDeskripsi() {
        return this.deskripsi;
    }
    
    public void setDeskripsi(String deskripsi) {
        this.deskripsi = deskripsi;
    }




}


